server:
  port: 8000
django:
  dataSources:
    dev:
      connectionString: mongodb://10.17.172.74:27017
  daoFactories:
    global:
      dataSourceName: dev
      database: testdb
  cache:
    defaultConfig:
      maxSize: 1000
      expireAfterAccessMills: -1
      expireAfterWriteMills: -1
      weakReference: false
      softReference: true
    classes:
      io.github.guchdes.django.example.Bag:
        maxSize: 5000
        expireAfterAccessMills: 600000
